apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/argoproj/argo-cd/examples/k8s-rbac/argocd-server-applications/argocd-server-rbac-clusterrole.yaml?ref=v3.2.0
  - github.com/argoproj/argo-cd/examples/k8s-rbac/argocd-server-applications/argocd-server-rbac-clusterrolebinding.yaml?ref=v3.2.0
  - github.com/argoproj/argo-cd/examples/k8s-rbac/argocd-server-applications/argocd-notifications-controller-rbac-clusterrole.yaml?ref=v3.2.0
  - github.com/argoproj/argo-cd/examples/k8s-rbac/argocd-server-applications/argocd-notifications-controller-rbac-clusterrolebinding.yaml?ref=v3.2.0